export const ResponseTypes = {
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
};

export const UserRoles = {
  EMPLOYEE: "EMPLOYEE",
  HM: "HM",
  HR: "HR",
  ADMIN: "ADMIN",
};
export const ReferralLevels = {
  RESUME_SCREENING: "RESUME_SCREENING",
  L1: "L1",
  L2: "L2",
  HR: "HR",
};

export const ReferralStatus = {
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
};

export const JobStatus = {
  OPEN: "OPEN",
  CLOSED: "CLOSED",
  ONHOLD: "ONHOLD",
};

export const PURPOSE = {
  UPDATE: "UPDATE",
  CHECK_REFERRAL: "CHECK_REFERRAL",
};

export const COLUMNS = {
  JOB_ID: 'JOB_ID',
  JOB_STATUS: 'JOB_STATUS',
  JOB_TITLE: 'JOB_TITLE',
  JOB_VISIBILITY: 'JOB_VISIBILITY',
  REFERRAL_NAME: 'REFERRAL_NAME',
  EMPLOYEE_ID: 'EMPLOYEE_ID',
  EMPLOYEE_ROLE:'EMPLOYEE_ROLE',
  CURRENT_LEVEL: 'CURRENT_LEVEL',
  CURRENT_STATUS: 'CURRENT_STATUS',
  PROGRESS: 'PROGRESS',
  RESUME: 'RESUME',
  HIRE_REJECT: 'HIRE_REJECT'
}
